#list of analysis levels in the bids app
analysis_levels: &analysis_levels
 - participant


#mapping from analysis_level to set of target rules or files
targets_by_analysis_level:
  participant:
    - 'all'  # if '', then the first rule is run

#this configures the pybids grabber - create an entry for each type of input you want to grab
# indexed by name of input
#   dictionary for each input is passed directly to pybids get()
#    https://bids-standard.github.io/pybids/generated/bids.layout.BIDSLayout.html#bids.layout.BIDSLayout.get

pybids_inputs:
  pial:
    filters:
      suffix: pial
      extension: .surf.gii
    wildcards:
      - subject
      - session
      - hemi
      - den
  wm:
    filters:
      suffix: wm
      extension: .surf.gii
    wildcards:
      - subject
      - session
      - hemi
      - den
  midthickness:
    filters:
      suffix: midthickness
      extension: .surf.gii
    wildcards:
      - subject
      - session
      - hemi
      - den
  data:
    filters:
      extension: .nii.gz
    wildcards:
      - subject
      - session

#configuration for the command-line parameters to make available
# passed on the argparse add_argument()
parse_args:

#---  core BIDS-app options --- (do not modify below)

  bids_dir:
    help: The directory with the input dataset formatted according
          to the BIDS standard.

  output_dir:
    help: The directory where the output files
          should be stored. If you are running group level analysis
          this folder should be prepopulated with the results of the
          participant level analysis.

  analysis_level:
    help: Level of the analysis that will be performed.
    choices: *analysis_levels

  --participant-label:
    help: The label(s) of the participant(s) that should be analyzed. The label
          corresponds to sub-<participant_label> from the BIDS spec
          (so it does not include "sub-"). If this parameter is not
          provided all subjects should be analyzed. Multiple
          participants can be specified with a space separated list.
    nargs: '+'

  --exclude-participant-label:
    help: The label(s) of the participant(s) that should be excluded. The label
          corresponds to sub-<participant_label> from the BIDS spec
          (so it does not include "sub-"). If this parameter is not
          provided all subjects should be analyzed. Multiple
          participants can be specified with a space separated list.
    nargs: '+'

  --derivatives:
    help: 'Path(s) to a derivatives dataset, for folder(s) that contains multiple derivatives datasets (default: %(default)s) '
    default: False
    action: store_true


 # custom command-line parameters can then be added, these will get added to the config and also accessible to plugins
 # below are examples for plugin and custom parameters (e.g. config['smoothing_fwhm'])
  --skip-bids-validation:
    help: 'Skip validation of BIDS dataset. BIDS validation is performed by
          default using the bids-validator plugin (if installed/enabled) or with the pybids
          validator implementation (if bids-validator is not installed/enabled).'
    dest: "plugins.validator.skip"
    action: "store_true"
    default: False

  --param:
    help: name of parameter



#--- workflow specific configuration -- below is just an example:


#singularity containers
containers:
  workbench: docker://brainlife/connectome_workbench:1.5.0-freesurfer-update